// <auto-generated />
using System;
using DesafioSuperHerois.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioSuperHerois.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioSuperHerois.Models.Herois", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("NomeHeroi")
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Herois");
                });

            modelBuilder.Entity("DesafioSuperHerois.Models.HeroisSuperpoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HeroiId")
                        .HasColumnType("int");

                    b.Property<int?>("HeroisId")
                        .HasColumnType("int");

                    b.Property<int>("SuperpoderId")
                        .HasColumnType("int");

                    b.Property<int?>("SuperpoderesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroisId");

                    b.HasIndex("SuperpoderesId");

                    b.ToTable("HeroisSuperpoderes");
                });

            modelBuilder.Entity("DesafioSuperHerois.Models.Superpoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Superpoder")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Superpoderes");
                });

            modelBuilder.Entity("DesafioSuperHerois.Models.HeroisSuperpoderes", b =>
                {
                    b.HasOne("DesafioSuperHerois.Models.Herois", "Herois")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("HeroisId");

                    b.HasOne("DesafioSuperHerois.Models.Superpoderes", "Superpoderes")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("SuperpoderesId");
                });
#pragma warning restore 612, 618
        }
    }
}
